---
name: zls_master
description: Zig LSP implementation + Zig Language Server (latest commit from 'master' branch).
homepage: https://github.com/zigtools/zls
licenses:
  - MIT
languages:
  - Zig
categories:
  - LSP

source:
  id: pkg:generic/zigtools/zls@master
  download_url: https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/master/
  download:
    - target: darwin_arm64
      files:
        zls: https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/master/aarch64-macos/zls
      bin: zls
    - target: darwin_x64
      files:
        zls: https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/master/x86_64-macos/zls
      bin: zls
    - target: linux_arm64
      files:
        zls: https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/master/aarch64-linux/zls
      bin: zls
    - target: linux_x64
      files:
        zls: https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/master/x86_64-linux/zls
      bin: zls
    - target: linux_x86
      files:
        zls: https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/master/x86-linux/zls
      bin: zls
    - target: win_x86
      files:
        zls.exe: https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/master/x86-windows/zls.exe
      bin: zls.exe
    - target: win_x64
      files:
        zls.exe: https://zigtools-releases.nyc3.digitaloceanspaces.com/zls/master/x86_64-windows/zls.exe
      bin: zls.exe
  build:

schemas:
  lsp: vscode:https://raw.githubusercontent.com/ziglang/vscode-zig/master/package.json

bin:
  zls: "{{source.download.bin}}"
